name: Release Connector

on:
  push:
    tags:
      - 'snowflake/v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Extract connector and version
        id: version
        run: |
          TAG=${{ github.ref_name }}
          CONNECTOR=$(echo $TAG | cut -d'/' -f1)
          VERSION=$(echo $TAG | cut -d'/' -f2 | sed 's/v//')
          echo "connector=$CONNECTOR" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push connector docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/hasura/ndc-snowflake-jdbc:v${{ steps.version.outputs.version }}
          build-args: |
            SOURCE=snowflake
            JOOQ_PRO_EMAIL=${{ secrets.JOOQ_PRO_EMAIL }}
            JOOQ_PRO_LICENSE=${{ secrets.JOOQ_PRO_LICENSE }}

      - name: Build and push CLI docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.cli
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/hasura/ndc-snowflake-cli:v${{ steps.version.outputs.version }}
          build-args: |
            SOURCE=snowflake
            JOOQ_PRO_EMAIL=${{ secrets.JOOQ_PRO_EMAIL }}
            JOOQ_PRO_LICENSE=${{ secrets.JOOQ_PRO_LICENSE }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ steps.version.outputs.connector }} v${{ steps.version.outputs.version }}"
          generate_release_notes: true
